namespace NeweysTools.VictronData
{
    public class Pvinverter
    {
        public float Ac_l1_power { get; set; }
        public float Ac_l1_current { get; set; }
        public float Ac_l1_energy_forward { get; set; }
        public float Ac_l1_voltage { get; set; }
        public float Ac_powerlimit { get; set; }
        public float Ac_energy_forward { get; set; }
        public object Ac_l2_current { get; set; }
        public object Ac_l2_energy_forward { get; set; }
        public object Ac_l2_power { get; set; }
        public object Ac_l2_voltage { get; set; }
        public object Ac_l3_current { get; set; }
        public object Ac_l3_energy_forward { get; set; }
        public object Ac_l3_power { get; set; }
        public object Ac_l3_voltage { get; set; }
        public float Ac_maxpower { get; set; }
        public float Ac_power { get; set; }
        public int Connected { get; set; }
        public string Customname { get; set; }
        public string Datamanagerversion { get; set; }
        public int Deviceinstance { get; set; }
        public object Errorcode { get; set; }
        public string Firmwareversion { get; set; }
        public int Froniusdevicetype { get; set; }
        public string Mgmt_connection { get; set; }
        public string Mgmt_processname { get; set; }
        public string Mgmt_processversion { get; set; }
        public int Position { get; set; }
        public int Productid { get; set; }
        public string Productname { get; set; }
        public string Serial { get; set; }
        public int Statuscode { get; set; }
        public float Ac_current { get; set; }
        public float Ac_voltage { get; set; }
        //public list Allowedroles { get; set; }
        public int Devicetype { get; set; }
        public object Phasesequence { get; set; }
        public string Role { get; set; }
    }

    public class Solarcharger
    {
        public float Yield_power { get; set; }
        public float Yield_system { get; set; }
        public float Yield_user { get; set; }
        public float Pv_v { get; set; }
        public float Dc_0_current { get; set; }
        public float Dc_0_voltage { get; set; }
        public int Capabilities_capabilities1 { get; set; }
        public int Connected { get; set; }
        public string Customname { get; set; }
        public int Deviceinstance { get; set; }
        public int Deviceoffreason { get; set; }
        public List<SolarchargerDevice> Devices { get; set; } = new List<SolarchargerDevice> ();
        public int Errorcode { get; set; }
        public int Firmwareversion { get; set; }
        public int Groupid { get; set; }
        public object Hardwareversion { get; set; }
        public int History_overall_daysavailable { get; set; }
        public int History_overall_lasterror1 { get; set; }
        public int History_overall_lasterror2 { get; set; }
        public int History_overall_lasterror3 { get; set; }
        public int History_overall_lasterror4 { get; set; }
        public float History_overall_maxbatteryvoltage { get; set; }
        public float History_overall_maxpvvoltage { get; set; }
        public float History_overall_minbatteryvoltage { get; set; }
        public object Link_batterycurrent { get; set; }
        public float Link_chargecurrent { get; set; }
        public float Link_chargevoltage { get; set; }
        public int Link_networkmode { get; set; }
        public int Link_networkstatus { get; set; }
        public float Link_temperaturesense { get; set; }
        public int Link_temperaturesenseactive { get; set; }
        public float Link_voltagesense { get; set; }
        public int Link_voltagesenseactive { get; set; }
        public int Load_state { get; set; }
        public string Mgmt_connection { get; set; }
        public string Mgmt_processname { get; set; }
        public string Mgmt_processversion { get; set; }
        public int Mode { get; set; }
        public int Mppoperationmode { get; set; }
        public int Nroftrackers { get; set; }
        public int Productid { get; set; }
        public string Productname { get; set; }
        public int Relay_0_state { get; set; }
        public string Serial { get; set; }
        public int Settings_batteryvoltagesetting { get; set; }
        public int Settings_bmspresent { get; set; }
        public float Settings_chargecurrentlimit { get; set; }
        public int State { get; set; }
        public int Vedirect_hexchecksumerrors { get; set; }
        public int Vedirect_hexinvalidcharactererrors { get; set; }
        public int Vedirect_hexunfinishederrors { get; set; }
        public int Vedirect_textchecksumerrors { get; set; }
        public int Vedirect_textparseerror { get; set; }
        public int Vedirect_textunfinishederrors { get; set; }
        public object Pv_isolationresistance { get; set; }
        public float Dc_0_temperature { get; set; }
        public int Alarms_highvoltage { get; set; }
        public int Alarms_lowvoltage { get; set; }
        public object Link_yield_power { get; set; }
        public int N2kdeviceinstance { get; set; }
        public int N2kuniquenumber { get; set; }
        public object Nrofoutputs { get; set; }
    }

    public class SolarchargerDevice
    {
        public string Customname { get; set; }
        public int Deviceinstance { get; set; }
        public int Firmwareversion { get; set; }
        public int Productid { get; set; }
        public string Productname { get; set; }
        public string Servicename { get; set; }
        public object Vreglink { get; set; }
        public int Nad { get; set; }
    }

    public class HistoryDailyEntry
    {
        public object consumption { get; set; }
        public int lasterror1 { get; set; }
        public int lasterror2 { get; set; }
        public int lasterror3 { get; set; }
        public int lasterror4 { get; set; }
        public float maxbatterycurrent { get; set; }
        public float maxbatteryvoltage { get; set; }
        public float maxpower { get; set; }
        public float maxpvvoltage { get; set; }
        public float minbatteryvoltage { get; set; }
        public int nr { get; set; }
        public float timeinabsorption { get; set; }
        public float timeinbulk { get; set; }
        public float timeinfloat { get; set; }
        public float yield { get; set; }
        public object pv_0_maxpower { get; set; }
        public object pv_0_maxvoltage { get; set; }
        public object pv_0_yield { get; set; }
    }

    public class Battery
    {
        public int Alarms_alarm { get; set; }
        public int Alarms_fuseblown { get; set; }
        public int Alarms_highinternaltemperature { get; set; }
        public int Alarms_hightemperature { get; set; }
        public int Alarms_highvoltage { get; set; }
        public int Alarms_lowsoc { get; set; }
        public int Alarms_lowtemperature { get; set; }
        public int Alarms_lowvoltage { get; set; }
        public int Connected { get; set; }
        public float Consumedamphours { get; set; }
        public string Customname { get; set; }
        public float Dc_0_current { get; set; }
        public int Dc_0_power { get; set; }
        public object Dc_0_temperature { get; set; }
        public float Dc_0_voltage { get; set; }
        public int Deviceinstance { get; set; }
        public List<BatteryDevice> Devices { get; set; } = new List<BatteryDevice> ();
        public object Errorcode { get; set; }
        public int Firmwareversion { get; set; }
        public object Hardwareversion { get; set; }
        public int History_automaticsyncs { get; set; }
        public float History_averagedischarge { get; set; }
        public int History_canbecleared { get; set; }
        public int History_chargecycles { get; set; }
        public object History_chargedenergy { get; set; }
        public object History_clear { get; set; }
        public float History_deepestdischarge { get; set; }
        public object History_dischargedenergy { get; set; }
        public int History_fulldischarges { get; set; }
        public int History_highvoltagealarms { get; set; }
        public float History_lastdischarge { get; set; }
        public int History_lowvoltagealarms { get; set; }
        public float History_maximumvoltage { get; set; }
        public float History_minimumvoltage { get; set; }
        public int History_timesincelastfullcharge { get; set; }
        public float History_totalahdrawn { get; set; }
        public string Mgmt_connection { get; set; }
        public string Mgmt_processname { get; set; }
        public string Mgmt_processversion { get; set; }
        public int N2kdeviceinstance { get; set; }
        public int N2kuniquenumber { get; set; }
        public object Nrofdistributors { get; set; }
        public int Productid { get; set; }
        public string Productname { get; set; }
        public int Relay_0_state { get; set; }
        public string Serial { get; set; }
        public float Settings_alarm_highbatterytemperature { get; set; }
        public float Settings_alarm_highbatterytemperatureclear { get; set; }
        public float Settings_alarm_highvoltage { get; set; }
        public float Settings_alarm_highvoltageclear { get; set; }
        public float Settings_alarm_lowbatterytemperature { get; set; }
        public float Settings_alarm_lowbatterytemperatureclear { get; set; }
        public float Settings_alarm_lowsoc { get; set; }
        public float Settings_alarm_lowsocclear { get; set; }
        public float Settings_alarm_lowvoltage { get; set; }
        public float Settings_alarm_lowvoltageclear { get; set; }
        public int Settings_battery_capacity { get; set; }
        public int Settings_battery_chargeefficiency { get; set; }
        public int Settings_battery_chargeddetectiontime { get; set; }
        public float Settings_battery_chargedvoltage { get; set; }
        public int Settings_battery_currentoffset { get; set; }
        public float Settings_battery_currentthreshold { get; set; }
        public float Settings_battery_dischargefloor { get; set; }
        public int Settings_battery_locked { get; set; }
        public float Settings_battery_peukertexponent { get; set; }
        public int Settings_battery_synchronize { get; set; }
        public int Settings_battery_ttgaveragingperiod { get; set; }
        public float Settings_battery_tailcurrent { get; set; }
        public int Settings_battery_zerocurrent { get; set; }
        public object Settings_bluetoothmode { get; set; }
        public int Settings_dischargefloorlinkedtorelay { get; set; }
        public int Settings_hassettings { get; set; }
        public int Settings_hastemperature { get; set; }
        public int Settings_relay_fuseblown { get; set; }
        public float Settings_relay_highbatterytemperature { get; set; }
        public float Settings_relay_highbatterytemperatureclear { get; set; }
        public float Settings_relay_highvoltage { get; set; }
        public float Settings_relay_highvoltageclear { get; set; }
        public float Settings_relay_lowbatterytemperature { get; set; }
        public float Settings_relay_lowbatterytemperatureclear { get; set; }
        public float Settings_relay_lowsoc { get; set; }
        public float Settings_relay_lowsocclear { get; set; }
        public float Settings_relay_lowvoltage { get; set; }
        public float Settings_relay_lowvoltageclear { get; set; }
        public int Settings_relay_minclosetime { get; set; }
        public int Settings_relay_mode { get; set; }
        public int Settings_relay_offdelay { get; set; }
        public int Settings_restoredefaults { get; set; }
        public float Soc { get; set; }
        public object Timetogo { get; set; }
    }

    public class BatteryDevice
    {
        public string Customname { get; set; }
        public int Deviceinstance { get; set; }
        public int Firmwareversion { get; set; }
        public int Nad { get; set; }
        public int Productid { get; set; }
        public string Productname { get; set; }
        public string Servicename { get; set; }
        public object Vreglink { get; set; }
    }

    public class Grid
    {
        public float Ac_l1_power { get; set; }
        public float Ac_l1_current { get; set; }
        public float Ac_l1_energy_forward { get; set; }
        public float Ac_l1_energy_reverse { get; set; }
        public float Ac_l1_voltage { get; set; }
        public float Ac_current { get; set; }
        public float Ac_energy_forward { get; set; }
        public float Ac_energy_reverse { get; set; }
        public object Ac_l2_current { get; set; }
        public object Ac_l2_energy_forward { get; set; }
        public object Ac_l2_energy_reverse { get; set; }
        public object Ac_l2_power { get; set; }
        public object Ac_l2_voltage { get; set; }
        public object Ac_l3_current { get; set; }
        public object Ac_l3_energy_forward { get; set; }
        public object Ac_l3_energy_reverse { get; set; }
        public object Ac_l3_power { get; set; }
        public object Ac_l3_voltage { get; set; }
        public float Ac_power { get; set; }
        public float Ac_voltage { get; set; }
        //public list Allowedroles { get; set; }
        public int Connected { get; set; }
        public string Customname { get; set; }
        public int Deviceinstance { get; set; }
        public int Devicetype { get; set; }
        public int Errorcode { get; set; }
        public int Firmwareversion { get; set; }
        public string Mgmt_connection { get; set; }
        public string Mgmt_processname { get; set; }
        public string Mgmt_processversion { get; set; }
        public object Phasesequence { get; set; }
        public int Productid { get; set; }
        public string Productname { get; set; }
        public string Role { get; set; }
        public string Serial { get; set; }
    }

    public class Vebus
    {
        public int Hub4_l1_acpowersetpoint { get; set; }
        public int Hub4_l1_currentlimitedduetohightemp { get; set; }
        public int Hub4_l1_frequencyvariationoccurred { get; set; }
        public int Hub4_l1_maxfeedinpower { get; set; }
        public int Hub4_l1_offsetaddedtovoltagesetpoint { get; set; }
        public int Hub4_assistantid { get; set; }
        public int Hub4_disablecharge { get; set; }
        public int Hub4_disablefeedin { get; set; }
        public int Hub4_donotfeedinovervoltage { get; set; }
        public int Hub4_fixsolaroffsetto100mv { get; set; }
        public int Hub4_sustain { get; set; }
        public int Hub4_targetpowerismaxfeedin { get; set; }
        public int Ac_activein_activeinput { get; set; }
        public int Ac_activein_connected { get; set; }
        public float Ac_activein_currentlimit { get; set; }
        public int Ac_activein_currentlimitisadjustable { get; set; }
        public float Ac_activein_l1_f { get; set; }
        public float Ac_activein_l1_i { get; set; }
        public int Ac_activein_l1_p { get; set; }
        public int Ac_activein_l1_s { get; set; }
        public float Ac_activein_l1_v { get; set; }
        public object Ac_activein_l2_f { get; set; }
        public object Ac_activein_l2_i { get; set; }
        public object Ac_activein_l2_p { get; set; }
        public object Ac_activein_l2_s { get; set; }
        public object Ac_activein_l2_v { get; set; }
        public object Ac_activein_l3_f { get; set; }
        public object Ac_activein_l3_i { get; set; }
        public object Ac_activein_l3_p { get; set; }
        public object Ac_activein_l3_s { get; set; }
        public object Ac_activein_l3_v { get; set; }
        public int Ac_activein_p { get; set; }
        public int Ac_activein_s { get; set; }
        public float Ac_in_1_currentlimit { get; set; }
        public int Ac_in_1_currentlimitisadjustable { get; set; }
        public float Ac_in_2_currentlimit { get; set; }
        public int Ac_in_2_currentlimitisadjustable { get; set; }
        public int Ac_numberofacinputs { get; set; }
        public int Ac_numberofphases { get; set; }
        public float Ac_out_l1_f { get; set; }
        public float Ac_out_l1_i { get; set; }
        public int Ac_out_l1_p { get; set; }
        public int Ac_out_l1_s { get; set; }
        public float Ac_out_l1_v { get; set; }
        public object Ac_out_l2_f { get; set; }
        public object Ac_out_l2_i { get; set; }
        public object Ac_out_l2_p { get; set; }
        public object Ac_out_l2_s { get; set; }
        public object Ac_out_l2_v { get; set; }
        public object Ac_out_l3_f { get; set; }
        public object Ac_out_l3_i { get; set; }
        public object Ac_out_l3_p { get; set; }
        public object Ac_out_l3_s { get; set; }
        public object Ac_out_l3_v { get; set; }
        public int Ac_out_p { get; set; }
        public int Ac_out_s { get; set; }
        public int Ac_powermeasurementtype { get; set; }
        public int Ac_state_ignoreacin1 { get; set; }
        public int Ac_state_ignoreacin2 { get; set; }
        public object Ac_state_splitphasel2passthru { get; set; }
        public object Acsensor_0_current { get; set; }
        public object Acsensor_0_energy { get; set; }
        public object Acsensor_0_location { get; set; }
        public object Acsensor_0_phase { get; set; }
        public object Acsensor_0_power { get; set; }
        public object Acsensor_0_voltage { get; set; }
        public object Acsensor_1_current { get; set; }
        public object Acsensor_1_energy { get; set; }
        public object Acsensor_1_location { get; set; }
        public object Acsensor_1_phase { get; set; }
        public object Acsensor_1_power { get; set; }
        public object Acsensor_1_voltage { get; set; }
        public object Acsensor_2_current { get; set; }
        public object Acsensor_2_energy { get; set; }
        public object Acsensor_2_location { get; set; }
        public object Acsensor_2_phase { get; set; }
        public object Acsensor_2_power { get; set; }
        public object Acsensor_2_voltage { get; set; }
        public object Acsensor_3_current { get; set; }
        public object Acsensor_3_energy { get; set; }
        public object Acsensor_3_location { get; set; }
        public object Acsensor_3_phase { get; set; }
        public object Acsensor_3_power { get; set; }
        public object Acsensor_3_voltage { get; set; }
        public object Acsensor_4_current { get; set; }
        public object Acsensor_4_energy { get; set; }
        public object Acsensor_4_location { get; set; }
        public object Acsensor_4_phase { get; set; }
        public object Acsensor_4_power { get; set; }
        public object Acsensor_4_voltage { get; set; }
        public object Acsensor_5_current { get; set; }
        public object Acsensor_5_energy { get; set; }
        public object Acsensor_5_location { get; set; }
        public object Acsensor_5_phase { get; set; }
        public object Acsensor_5_power { get; set; }
        public object Acsensor_5_voltage { get; set; }
        public object Acsensor_6_current { get; set; }
        public object Acsensor_6_energy { get; set; }
        public object Acsensor_6_location { get; set; }
        public object Acsensor_6_phase { get; set; }
        public object Acsensor_6_power { get; set; }
        public object Acsensor_6_voltage { get; set; }
        public object Acsensor_7_current { get; set; }
        public object Acsensor_7_energy { get; set; }
        public object Acsensor_7_location { get; set; }
        public object Acsensor_7_phase { get; set; }
        public object Acsensor_7_power { get; set; }
        public object Acsensor_7_voltage { get; set; }
        public object Acsensor_8_current { get; set; }
        public object Acsensor_8_energy { get; set; }
        public object Acsensor_8_location { get; set; }
        public object Acsensor_8_phase { get; set; }
        public object Acsensor_8_power { get; set; }
        public object Acsensor_8_voltage { get; set; }
        public object Acsensor_count { get; set; }
        public int Alarms_gridlost { get; set; }
        public int Alarms_highdccurrent { get; set; }
        public int Alarms_highdcvoltage { get; set; }
        public int Alarms_hightemperature { get; set; }
        public int Alarms_l1_hightemperature { get; set; }
        public int Alarms_l1_lowbattery { get; set; }
        public int Alarms_l1_overload { get; set; }
        public int Alarms_l1_ripple { get; set; }
        public int Alarms_l2_hightemperature { get; set; }
        public int Alarms_l2_lowbattery { get; set; }
        public int Alarms_l2_overload { get; set; }
        public int Alarms_l2_ripple { get; set; }
        public int Alarms_l3_hightemperature { get; set; }
        public int Alarms_l3_lowbattery { get; set; }
        public int Alarms_l3_overload { get; set; }
        public int Alarms_l3_ripple { get; set; }
        public int Alarms_lowbattery { get; set; }
        public int Alarms_overload { get; set; }
        public int Alarms_phaserotation { get; set; }
        public int Alarms_ripple { get; set; }
        public int Alarms_temperaturesensor { get; set; }
        public int Alarms_voltagesensor { get; set; }
        public object Batteryoperationallimits_batterylowvoltage { get; set; }
        public object Batteryoperationallimits_maxchargecurrent { get; set; }
        public object Batteryoperationallimits_maxchargevoltage { get; set; }
        public object Batteryoperationallimits_maxdischargecurrent { get; set; }
        public float Batterysense_temperature { get; set; }
        public float Batterysense_voltage { get; set; }
        public int Bms_allowtocharge { get; set; }
        public int Bms_allowtochargerate { get; set; }
        public int Bms_allowtodischarge { get; set; }
        public int Bms_bmsexpected { get; set; }
        public int Bms_bmstype { get; set; }
        public int Bms_error { get; set; }
        public object Bms_prealarm { get; set; }
        public int Connected { get; set; }
        public string Customname { get; set; }
        public float Dc_0_current { get; set; }
        public float Dc_0_maxchargecurrent { get; set; }
        public int Dc_0_power { get; set; }
        public float Dc_0_temperature { get; set; }
        public float Dc_0_voltage { get; set; }
        public int Deviceinstance { get; set; }
        public List<VebusDevice> Devices { get; set; } = new List<VebusDevice> ();
        public float Energy_acin1toacout { get; set; }
        public float Energy_acin1toinverter { get; set; }
        public float Energy_acin2toacout { get; set; }
        public float Energy_acin2toinverter { get; set; }
        public float Energy_acouttoacin1 { get; set; }
        public float Energy_acouttoacin2 { get; set; }
        public float Energy_invertertoacin1 { get; set; }
        public float Energy_invertertoacin2 { get; set; }
        public float Energy_invertertoacout { get; set; }
        public float Energy_outtoinverter { get; set; }
        public float Extrabatterycurrent { get; set; }
        public int Firmwarefeatures_bolframe { get; set; }
        public int Firmwarefeatures_bolubatandtbatsense { get; set; }
        public int Firmwarefeatures_commandwriteviaid { get; set; }
        public int Firmwarefeatures_ibatsocbroadcast { get; set; }
        public int Firmwarefeatures_newpanelframe { get; set; }
        public int Firmwarefeatures_setchargestate { get; set; }
        public int Firmwaresubversion { get; set; }
        public int Firmwareversion { get; set; }
        public float Hub_chargevoltage { get; set; }
        public string Interfaces_mk2_connection { get; set; }
        public int Interfaces_mk2_productid { get; set; }
        public string Interfaces_mk2_productname { get; set; }
        public int Interfaces_mk2_status_busfreemode { get; set; }
        public int Interfaces_mk2_version { get; set; }
        public int Leds_absorption { get; set; }
        public int Leds_bulk { get; set; }
        public int Leds_float { get; set; }
        public int Leds_inverter { get; set; }
        public int Leds_lowbattery { get; set; }
        public int Leds_mains { get; set; }
        public int Leds_overload { get; set; }
        public int Leds_temperature { get; set; }
        public string Mgmt_connection { get; set; }
        public string Mgmt_processname { get; set; }
        public string Mgmt_processversion { get; set; }
        public int Mode { get; set; }
        public int Modeisadjustable { get; set; }
        public int Productid { get; set; }
        public string Productname { get; set; }
        public int Pvinverter_disable { get; set; }
        public int Quirks { get; set; }
        public int Redetectsystem { get; set; }
        public int Settings_alarm_system_gridlost { get; set; }
        public int Settings_systemsetup_acinput1 { get; set; }
        public int Settings_systemsetup_acinput2 { get; set; }
        public int Shortids { get; set; }
        public float Soc { get; set; }
        public int State { get; set; }
        public object Systemreset { get; set; }
        public int Vebuschargestate { get; set; }
        public int Vebuserror { get; set; }
        public int Vebusmainstate { get; set; }
        public int Vebussetchargestate { get; set; }
    }

    public class VebusDevice
    {
        //public list Assistants { get; set; }
        public int Extendstatus_acin2selected { get; set; }
        public int Extendstatus_chargedisabledduetolowtemp { get; set; }
        public int Extendstatus_chargeisdisabled { get; set; }
        public object Extendstatus_gridrelayreport_code { get; set; }
        public object Extendstatus_gridrelayreport_count { get; set; }
        public int Extendstatus_gridrelayreport_reset { get; set; }
        public int Extendstatus_highdccurrent { get; set; }
        public int Extendstatus_highdcvoltage { get; set; }
        public int Extendstatus_ignoreacin1 { get; set; }
        public int Extendstatus_ignoreacin2 { get; set; }
        public int Extendstatus_mainsplllocked { get; set; }
        public int Extendstatus_pcvpotmeteronzero { get; set; }
        public int Extendstatus_powerpackpreoverload { get; set; }
        public int Extendstatus_soctoolowtoinvert { get; set; }
        public int Extendstatus_sustainmode { get; set; }
        public int Extendstatus_switchoverinfo_connecting { get; set; }
        public int Extendstatus_switchoverinfo_delay { get; set; }
        public int Extendstatus_switchoverinfo_errorflags { get; set; }
        public int Extendstatus_temperaturehighforcebypass { get; set; }
        public int Extendstatus_vebusnetworkqualitycounter { get; set; }
        public int Extendstatus_waitingforrelaytest { get; set; }
        public int Interfaceprotectionlog_0_errorflags { get; set; }
        public int Interfaceprotectionlog_0_time { get; set; }
        public int Interfaceprotectionlog_1_errorflags { get; set; }
        public int Interfaceprotectionlog_1_time { get; set; }
        public object Interfaceprotectionlog_2_errorflags { get; set; }
        public object Interfaceprotectionlog_2_time { get; set; }
        public object Interfaceprotectionlog_3_errorflags { get; set; }
        public object Interfaceprotectionlog_3_time { get; set; }
        public object Interfaceprotectionlog_4_errorflags { get; set; }
        public object Interfaceprotectionlog_4_time { get; set; }
        public string Serialnumber { get; set; }
        public object Version { get; set; }
    }

    public class System
    {
        public float Ac_consumption_l1_power { get; set; }
        public float Ac_consumption_l1_current { get; set; }
        public object Ac_consumption_l2_current { get; set; }
        public object Ac_consumption_l2_power { get; set; }
        public object Ac_consumption_l3_current { get; set; }
        public object Ac_consumption_l3_power { get; set; }
        public int Ac_consumption_numberofphases { get; set; }
        public float Ac_activein_l1_current { get; set; }
        public float Ac_activein_l1_power { get; set; }
        public object Ac_activein_l2_current { get; set; }
        public object Ac_activein_l2_power { get; set; }
        public object Ac_activein_l3_current { get; set; }
        public object Ac_activein_l3_power { get; set; }
        public int Ac_activein_numberofphases { get; set; }
        public int Ac_activein_source { get; set; }
        public float Ac_consumptiononinput_l1_current { get; set; }
        public int Ac_consumptiononinput_l1_power { get; set; }
        public object Ac_consumptiononinput_l2_current { get; set; }
        public object Ac_consumptiononinput_l2_power { get; set; }
        public object Ac_consumptiononinput_l3_current { get; set; }
        public object Ac_consumptiononinput_l3_power { get; set; }
        public int Ac_consumptiononinput_numberofphases { get; set; }
        public float Ac_consumptiononoutput_l1_current { get; set; }
        public float Ac_consumptiononoutput_l1_power { get; set; }
        public object Ac_consumptiononoutput_l2_current { get; set; }
        public object Ac_consumptiononoutput_l2_power { get; set; }
        public object Ac_consumptiononoutput_l3_current { get; set; }
        public object Ac_consumptiononoutput_l3_power { get; set; }
        public int Ac_consumptiononoutput_numberofphases { get; set; }
        public object Ac_genset_devicetype { get; set; }
        public object Ac_genset_l1_current { get; set; }
        public object Ac_genset_l1_power { get; set; }
        public object Ac_genset_l2_current { get; set; }
        public object Ac_genset_l2_power { get; set; }
        public object Ac_genset_l3_current { get; set; }
        public object Ac_genset_l3_power { get; set; }
        public object Ac_genset_laststarttime { get; set; }
        public object Ac_genset_numberofphases { get; set; }
        public object Ac_genset_productid { get; set; }
        public object Ac_genset_runningbyconditioncode { get; set; }
        public object Ac_genset_runtime { get; set; }
        public int Ac_grid_devicetype { get; set; }
        public float Ac_grid_l1_current { get; set; }
        public float Ac_grid_l1_power { get; set; }
        public object Ac_grid_l2_current { get; set; }
        public object Ac_grid_l2_power { get; set; }
        public object Ac_grid_l3_current { get; set; }
        public object Ac_grid_l3_power { get; set; }
        public int Ac_grid_numberofphases { get; set; }
        public int Ac_grid_productid { get; set; }
        public int Ac_in_0_connected { get; set; }
        public int Ac_in_0_deviceinstance { get; set; }
        public string Ac_in_0_servicename { get; set; }
        public string Ac_in_0_servicetype { get; set; }
        public int Ac_in_0_source { get; set; }
        public int Ac_in_0_vrmdeviceinstance { get; set; }
        public object Ac_in_1_connected { get; set; }
        public object Ac_in_1_deviceinstance { get; set; }
        public object Ac_in_1_servicename { get; set; }
        public object Ac_in_1_servicetype { get; set; }
        public object Ac_in_1_source { get; set; }
        public object Ac_in_1_vrmdeviceinstance { get; set; }
        public int Ac_in_numberofacinputs { get; set; }
        public object Ac_pvongenset_l1_current { get; set; }
        public object Ac_pvongenset_l1_power { get; set; }
        public object Ac_pvongenset_l2_current { get; set; }
        public object Ac_pvongenset_l2_power { get; set; }
        public object Ac_pvongenset_l3_current { get; set; }
        public object Ac_pvongenset_l3_power { get; set; }
        public object Ac_pvongenset_numberofphases { get; set; }
        public float Ac_pvongrid_l1_current { get; set; }
        public float Ac_pvongrid_l1_power { get; set; }
        public object Ac_pvongrid_l2_current { get; set; }
        public object Ac_pvongrid_l2_power { get; set; }
        public object Ac_pvongrid_l3_current { get; set; }
        public object Ac_pvongrid_l3_power { get; set; }
        public int Ac_pvongrid_numberofphases { get; set; }
        public float Ac_pvonoutput_l1_current { get; set; }
        public float Ac_pvonoutput_l1_power { get; set; }
        public object Ac_pvonoutput_l2_current { get; set; }
        public object Ac_pvonoutput_l2_power { get; set; }
        public object Ac_pvonoutput_l3_current { get; set; }
        public object Ac_pvonoutput_l3_power { get; set; }
        public int Ac_pvonoutput_numberofphases { get; set; }
        public string Serial { get; set; }
        public string Activebatteryservice { get; set; }
        public string Autoselectedbatterymeasurement { get; set; }
        public object Autoselectedbatteryservice { get; set; }
        public string Autoselectedtemperatureservice { get; set; }
        public string Availablebatteries { get; set; }
        //public dic Availablebatterymeasurements { get; set; } // error in the topic parser not defining this element correctly. Leave for LN to troubleshoot
        public string Availablebatteryservices { get; set; }
        //public dict Availabletemperatureservices { get; set; }// error in the topic parser not defining this element correctly. Leave for LN to troubleshoot
        //public list Batteries { get; set; }// error in the topic parser not defining this element correctly. Leave for LN to troubleshoot
        public int Buzzer_state { get; set; }
        public int Connected { get; set; }
        public int Control_batterycurrentsense { get; set; }
        public int Control_batteryvoltagesense { get; set; }
        public int Control_bmsparameters { get; set; }
        public int Control_dvcc { get; set; }
        public float Control_effectivechargevoltage { get; set; }
        public int Control_extrabatterycurrent { get; set; }
        public bool Control_maxchargecurrent { get; set; }
        public int Control_scheduledcharge { get; set; }
        public int Control_solarchargecurrent { get; set; }
        public int Control_solarchargevoltage { get; set; }
        public int Control_solarchargertemperaturesense { get; set; }
        public int Control_solarchargervoltagesense { get; set; }
        public int Control_vebussoc { get; set; }
        public object Dc_alternator_power { get; set; }
        public object Dc_battery_alarms_circuitbreakertripped { get; set; }
        public string Dc_battery_batteryservice { get; set; }
        public float Dc_battery_consumedamphours { get; set; }
        public float Dc_battery_current { get; set; }
        public int Dc_battery_power { get; set; }
        public int Dc_battery_productid { get; set; }
        public float Dc_battery_soc { get; set; }
        public int Dc_battery_state { get; set; }
        public float Dc_battery_temperature { get; set; }
        public string Dc_battery_temperatureservice { get; set; }
        public object Dc_battery_timetogo { get; set; }
        public float Dc_battery_voltage { get; set; }
        public string Dc_battery_voltageservice { get; set; }
        public object Dc_charger_power { get; set; }
        public object Dc_fuelcell_power { get; set; }
        public float Dc_pv_current { get; set; }
        public float Dc_pv_power { get; set; }
        public int Dc_system_measurementtype { get; set; }
        public float Dc_system_power { get; set; }
        public float Dc_vebus_current { get; set; }
        public int Dc_vebus_power { get; set; }
        public int Debug_batteryoperationallimits_currentoffset { get; set; }
        public int Debug_batteryoperationallimits_solarvoltageoffset { get; set; }
        public int Debug_batteryoperationallimits_vebusvoltageoffset { get; set; }
        public int Deviceinstance { get; set; }
        public int Dvcc_alarms_firmwareinsufficient { get; set; }
        public int Dvcc_alarms_multiplebatteries { get; set; }
        public string Firmwarebuild { get; set; }
        public int Firmwareversion { get; set; }
        public object Gpsservice { get; set; }
        public object Hardwareversion { get; set; }
        public int Hub { get; set; }
        public string Mgmt_connection { get; set; }
        public string Mgmt_processname { get; set; }
        public string Mgmt_processversion { get; set; }
        public object Productid { get; set; }
        public object Productname { get; set; }
        //public List<Pv> Pvinvertersproductids { get; set; }
        public int Relay_0_state { get; set; }
        public int Relay_1_state { get; set; }
        public string Servicemapping_com_victronenergy_battery_0 { get; set; }
        public string Servicemapping_com_victronenergy_grid_30 { get; set; }
        public string Servicemapping_com_victronenergy_hub4_0 { get; set; }
        public string Servicemapping_com_victronenergy_pvinverter_20 { get; set; }
        public string Servicemapping_com_victronenergy_pvinverter_21 { get; set; }
        public string Servicemapping_com_victronenergy_pvinverter_22 { get; set; }
        public string Servicemapping_com_victronenergy_pvinverter_24 { get; set; }
        public string Servicemapping_com_victronenergy_pvinverter_32 { get; set; }
        public string Servicemapping_com_victronenergy_settings_0 { get; set; }
        public string Servicemapping_com_victronenergy_solarcharger_0 { get; set; }
        public string Servicemapping_com_victronenergy_solarcharger_277 { get; set; }
        public string Servicemapping_com_victronenergy_solarcharger_279 { get; set; }
        public string Servicemapping_com_victronenergy_solarcharger_280 { get; set; }
        public string Servicemapping_com_victronenergy_temperature_24 { get; set; }
        public string Servicemapping_com_victronenergy_temperature_25 { get; set; }
        public string Servicemapping_com_victronenergy_temperature_26 { get; set; }
        public string Servicemapping_com_victronenergy_temperature_27 { get; set; }
        public string Servicemapping_com_victronenergy_vebus_276 { get; set; }
        public string Servicemapping_com_victronenergy_vecan_0 { get; set; }
        public int Systemstate_batterylife { get; set; }
        public int Systemstate_chargedisabled { get; set; }
        public int Systemstate_dischargedisabled { get; set; }
        public int Systemstate_lowsoc { get; set; }
        public int Systemstate_slowcharge { get; set; }
        public int Systemstate_state { get; set; }
        public int Systemstate_userchargelimited { get; set; }
        public int Systemstate_userdischargelimited { get; set; }
        public string Systemtype { get; set; }
        public int Timers_timeoff { get; set; }
        public int Timers_timeongenerator { get; set; }
        public int Timers_timeongrid { get; set; }
        public int Timers_timeoninverter { get; set; }
        public string Vebusservice { get; set; }
    }

    public class Temperature
    {
        public int temperature { get; set; }
        public int Connected { get; set; }
        public string Customname { get; set; }
        public int Deviceinstance { get; set; }
        public int Filterlength { get; set; }
        public string Mgmt_connection { get; set; }
        public string Mgmt_processname { get; set; }
        public string Mgmt_processversion { get; set; }
        public float Offset { get; set; }
        public int Productid { get; set; }
        public string Productname { get; set; }
        public string Rawunit { get; set; }
        public float Rawvalue { get; set; }
        public float Scale { get; set; }
        public int Status { get; set; }
        public int Temperaturetype { get; set; }
    }

    public class AdcDevice
    {
        public int Function { get; set; }
        public string Label { get; set; }
    }

    public class Adc
    {
        public List<AdcDevice> Devices { get; set; } = new List<AdcDevice> ();
    }

    public class Fronius
    {
        public int Autodetect { get; set; }
        public float Scanprogress { get; set; }
    }

    public class Hub4
    {
        public int Alarms_nogridmeter { get; set; }
        public int Deviceinstance { get; set; }
        public object Maxchargepower { get; set; }
        public object Maxdischargepower { get; set; }
        public int Overrides_forcecharge { get; set; }
        public object Overrides_maxdischargepower { get; set; }
        public int Pvpowerlimiteractive { get; set; }
    }

    public class Logger
    {
        public int Buffer_count { get; set; }
        public int Buffer_errorstate { get; set; }
        public int Buffer_freediskspace { get; set; }
        public int Buffer_location { get; set; }
        public object Buffer_oldesttimestamp { get; set; }
        public int Storage_mountstate { get; set; }
        public int Vrm_connectionerror { get; set; }
        public object Vrm_connectionerrormessage { get; set; }
        public int Vrm_timelastcontact { get; set; }
    }

    public class Modbusclient
    {
        public bool Scan { get; set; }
        public object Scanprogress { get; set; }
    }

    public class Modbustcp
    {
        public string Lasterror_message { get; set; }
        public int Lasterror_timestamp { get; set; }
        public int Services_0_isactive { get; set; }
        public string Services_0_servicename { get; set; }
        public int Services_0_unitid { get; set; }
        public int Services_1_isactive { get; set; }
        public string Services_1_servicename { get; set; }
        public int Services_1_unitid { get; set; }
        public int Services_10_isactive { get; set; }
        public string Services_10_servicename { get; set; }
        public int Services_10_unitid { get; set; }
        public int Services_11_isactive { get; set; }
        public string Services_11_servicename { get; set; }
        public int Services_11_unitid { get; set; }
        public int Services_12_isactive { get; set; }
        public string Services_12_servicename { get; set; }
        public int Services_12_unitid { get; set; }
        public int Services_13_isactive { get; set; }
        public string Services_13_servicename { get; set; }
        public int Services_13_unitid { get; set; }
        public int Services_14_isactive { get; set; }
        public string Services_14_servicename { get; set; }
        public int Services_14_unitid { get; set; }
        public int Services_15_isactive { get; set; }
        public string Services_15_servicename { get; set; }
        public int Services_15_unitid { get; set; }
        public int Services_16_isactive { get; set; }
        public string Services_16_servicename { get; set; }
        public int Services_16_unitid { get; set; }
        public int Services_17_isactive { get; set; }
        public string Services_17_servicename { get; set; }
        public int Services_17_unitid { get; set; }
        public int Services_18_isactive { get; set; }
        public string Services_18_servicename { get; set; }
        public int Services_18_unitid { get; set; }
        public int Services_19_isactive { get; set; }
        public string Services_19_servicename { get; set; }
        public int Services_19_unitid { get; set; }
        public int Services_2_isactive { get; set; }
        public string Services_2_servicename { get; set; }
        public int Services_2_unitid { get; set; }
        public int Services_20_isactive { get; set; }
        public string Services_20_servicename { get; set; }
        public int Services_20_unitid { get; set; }
        public int Services_21_isactive { get; set; }
        public string Services_21_servicename { get; set; }
        public int Services_21_unitid { get; set; }
        public int Services_3_isactive { get; set; }
        public string Services_3_servicename { get; set; }
        public int Services_3_unitid { get; set; }
        public int Services_4_isactive { get; set; }
        public string Services_4_servicename { get; set; }
        public int Services_4_unitid { get; set; }
        public int Services_5_isactive { get; set; }
        public string Services_5_servicename { get; set; }
        public int Services_5_unitid { get; set; }
        public int Services_6_isactive { get; set; }
        public string Services_6_servicename { get; set; }
        public int Services_6_unitid { get; set; }
        public int Services_7_isactive { get; set; }
        public string Services_7_servicename { get; set; }
        public int Services_7_unitid { get; set; }
        public int Services_8_isactive { get; set; }
        public string Services_8_servicename { get; set; }
        public int Services_8_unitid { get; set; }
        public int Services_9_isactive { get; set; }
        public string Services_9_servicename { get; set; }
        public int Services_9_unitid { get; set; }
        public int Services_count { get; set; }
    }

    public class Platform
    {
        //public list Canbus_interfaces { get; set; }
        public int Services_accesspoint_enabled { get; set; }
    }

    public class Settings
    {
        public int Settings_alarm_audible { get; set; }
        public int Settings_alarm_system_gridlost { get; set; }
        public int Settings_alarm_vebus_highdccurrent { get; set; }
        public int Settings_alarm_vebus_highdcripple { get; set; }
        public int Settings_alarm_vebus_highdcvoltage { get; set; }
        public int Settings_alarm_vebus_hightemperature { get; set; }
        public int Settings_alarm_vebus_inverteroverload { get; set; }
        public int Settings_alarm_vebus_lowbattery { get; set; }
        public int Settings_alarm_vebus_temperaturesenseerror { get; set; }
        public int Settings_alarm_vebus_vebuserror { get; set; }
        public int Settings_alarm_vebus_voltagesenseerror { get; set; }
        public string Settings_ble_service_pincode { get; set; }
        public float Settings_cgwacs_acpowersetpoint { get; set; }
        public int Settings_cgwacs_batterylife_dischargedtime { get; set; }
        public int Settings_cgwacs_batterylife_flags { get; set; }
        public float Settings_cgwacs_batterylife_minimumsoclimit { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_0_day { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_0_duration { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_0_soc { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_0_start { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_1_day { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_1_duration { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_1_soc { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_1_start { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_2_day { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_2_duration { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_2_soc { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_2_start { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_3_day { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_3_duration { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_3_soc { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_3_start { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_4_day { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_4_duration { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_4_soc { get; set; }
        public int Settings_cgwacs_batterylife_schedule_charge_4_start { get; set; }
        public float Settings_cgwacs_batterylife_soclimit { get; set; }
        public int Settings_cgwacs_batterylife_state { get; set; }
        public string Settings_cgwacs_deviceids { get; set; }
        public int Settings_cgwacs_hub4mode { get; set; }
        public float Settings_cgwacs_maxchargepercentage { get; set; }
        public float Settings_cgwacs_maxchargepower { get; set; }
        public float Settings_cgwacs_maxdischargepercentage { get; set; }
        public float Settings_cgwacs_maxdischargepower { get; set; }
        public float Settings_cgwacs_maxfeedinpower { get; set; }
        public int Settings_cgwacs_overvoltagefeedin { get; set; }
        public int Settings_cgwacs_preventfeedback { get; set; }
        public int Settings_cgwacs_runwithoutgridmeter { get; set; }
        public string Settings_canbms_socketcancan1_customname { get; set; }
        public int Settings_canbms_socketcancan1_productid { get; set; }
        public int Settings_canbus_can0_profile { get; set; }
        public int Settings_canbus_can1_profile { get; set; }
        public List<SettingsDevice> Devices { get; set; } = new List<SettingsDevice> ();
        public int Settings_digitalinput_1_alarmsetting { get; set; }
        public int Settings_digitalinput_1_count { get; set; }
        public string Settings_digitalinput_1_customname { get; set; }
        public int Settings_digitalinput_1_invertalarm { get; set; }
        public int Settings_digitalinput_1_inverttranslation { get; set; }
        public float Settings_digitalinput_1_multiplier { get; set; }
        public int Settings_digitalinput_1_type { get; set; }
        public int Settings_digitalinput_2_alarmsetting { get; set; }
        public int Settings_digitalinput_2_count { get; set; }
        public string Settings_digitalinput_2_customname { get; set; }
        public int Settings_digitalinput_2_invertalarm { get; set; }
        public int Settings_digitalinput_2_inverttranslation { get; set; }
        public float Settings_digitalinput_2_multiplier { get; set; }
        public int Settings_digitalinput_2_type { get; set; }
        public int Settings_digitalinput_3_alarmsetting { get; set; }
        public int Settings_digitalinput_3_count { get; set; }
        public string Settings_digitalinput_3_customname { get; set; }
        public int Settings_digitalinput_3_invertalarm { get; set; }
        public int Settings_digitalinput_3_inverttranslation { get; set; }
        public float Settings_digitalinput_3_multiplier { get; set; }
        public int Settings_digitalinput_3_type { get; set; }
        public int Settings_digitalinput_4_alarmsetting { get; set; }
        public int Settings_digitalinput_4_count { get; set; }
        public string Settings_digitalinput_4_customname { get; set; }
        public int Settings_digitalinput_4_invertalarm { get; set; }
        public int Settings_digitalinput_4_inverttranslation { get; set; }
        public float Settings_digitalinput_4_multiplier { get; set; }
        public int Settings_digitalinput_4_type { get; set; }
        public int Settings_fischerpanda0_acload_enabled { get; set; }
        public int Settings_fischerpanda0_acload_measurement { get; set; }
        public int Settings_fischerpanda0_acload_quiethoursstartvalue { get; set; }
        public int Settings_fischerpanda0_acload_quiethoursstopvalue { get; set; }
        public int Settings_fischerpanda0_acload_starttimer { get; set; }
        public int Settings_fischerpanda0_acload_startvalue { get; set; }
        public int Settings_fischerpanda0_acload_stoptimer { get; set; }
        public int Settings_fischerpanda0_acload_stopvalue { get; set; }
        public string Settings_fischerpanda0_accumulateddaily { get; set; }
        public int Settings_fischerpanda0_accumulatedtotal { get; set; }
        public int Settings_fischerpanda0_alarms_nogeneratoratacin { get; set; }
        public int Settings_fischerpanda0_autostartenabled { get; set; }
        public int Settings_fischerpanda0_batterycurrent_enabled { get; set; }
        public float Settings_fischerpanda0_batterycurrent_quiethoursstartvalue { get; set; }
        public float Settings_fischerpanda0_batterycurrent_quiethoursstopvalue { get; set; }
        public int Settings_fischerpanda0_batterycurrent_starttimer { get; set; }
        public float Settings_fischerpanda0_batterycurrent_startvalue { get; set; }
        public int Settings_fischerpanda0_batterycurrent_stoptimer { get; set; }
        public float Settings_fischerpanda0_batterycurrent_stopvalue { get; set; }
        public string Settings_fischerpanda0_batteryservice { get; set; }
        public int Settings_fischerpanda0_batteryvoltage_enabled { get; set; }
        public float Settings_fischerpanda0_batteryvoltage_quiethoursstartvalue { get; set; }
        public float Settings_fischerpanda0_batteryvoltage_quiethoursstopvalue { get; set; }
        public int Settings_fischerpanda0_batteryvoltage_starttimer { get; set; }
        public float Settings_fischerpanda0_batteryvoltage_startvalue { get; set; }
        public int Settings_fischerpanda0_batteryvoltage_stoptimer { get; set; }
        public float Settings_fischerpanda0_batteryvoltage_stopvalue { get; set; }
        public int Settings_fischerpanda0_inverterhightemp_enabled { get; set; }
        public int Settings_fischerpanda0_inverterhightemp_starttimer { get; set; }
        public int Settings_fischerpanda0_inverterhightemp_stoptimer { get; set; }
        public int Settings_fischerpanda0_inverteroverload_enabled { get; set; }
        public int Settings_fischerpanda0_inverteroverload_starttimer { get; set; }
        public int Settings_fischerpanda0_inverteroverload_stoptimer { get; set; }
        public int Settings_fischerpanda0_minimumruntime { get; set; }
        public int Settings_fischerpanda0_onlosscommunication { get; set; }
        public int Settings_fischerpanda0_quiethours_enabled { get; set; }
        public int Settings_fischerpanda0_quiethours_endtime { get; set; }
        public int Settings_fischerpanda0_quiethours_starttime { get; set; }
        public int Settings_fischerpanda0_soc_enabled { get; set; }
        public int Settings_fischerpanda0_soc_quiethoursstartvalue { get; set; }
        public int Settings_fischerpanda0_soc_quiethoursstopvalue { get; set; }
        public int Settings_fischerpanda0_soc_startvalue { get; set; }
        public int Settings_fischerpanda0_soc_stopvalue { get; set; }
        public int Settings_fischerpanda0_stopwhenac1available { get; set; }
        public int Settings_fischerpanda0_testrun_duration { get; set; }
        public int Settings_fischerpanda0_testrun_enabled { get; set; }
        public int Settings_fischerpanda0_testrun_interval { get; set; }
        public int Settings_fischerpanda0_testrun_runtillbatteryfull { get; set; }
        public int Settings_fischerpanda0_testrun_skipruntime { get; set; }
        public int Settings_fischerpanda0_testrun_startdate { get; set; }
        public int Settings_fischerpanda0_testrun_starttime { get; set; }
        public int Settings_fronius_autoscan { get; set; }
        public string Settings_fronius_ipaddresses { get; set; }
        public string Settings_fronius_inverterids { get; set; }
        public string Settings_fronius_inverters_i224_16777215_customname { get; set; }
        public int Settings_fronius_inverters_i224_16777215_isactive { get; set; }
        public float Settings_fronius_inverters_i224_16777215_l1energy { get; set; }
        public float Settings_fronius_inverters_i224_16777215_l2energy { get; set; }
        public float Settings_fronius_inverters_i224_16777215_l3energy { get; set; }
        public int Settings_fronius_inverters_i224_16777215_phase { get; set; }
        public int Settings_fronius_inverters_i224_16777215_phasecount { get; set; }
        public int Settings_fronius_inverters_i224_16777215_position { get; set; }
        public string Settings_fronius_inverters_i224_16777215_serialnumber { get; set; }
        public string Settings_fronius_inverters_i224_578545_customname { get; set; }
        public int Settings_fronius_inverters_i224_578545_isactive { get; set; }
        public float Settings_fronius_inverters_i224_578545_l1energy { get; set; }
        public float Settings_fronius_inverters_i224_578545_l2energy { get; set; }
        public float Settings_fronius_inverters_i224_578545_l3energy { get; set; }
        public int Settings_fronius_inverters_i224_578545_phase { get; set; }
        public int Settings_fronius_inverters_i224_578545_phasecount { get; set; }
        public int Settings_fronius_inverters_i224_578545_position { get; set; }
        public string Settings_fronius_inverters_i224_578545_serialnumber { get; set; }
        public string Settings_fronius_inverters_i81_322735_customname { get; set; }
        public int Settings_fronius_inverters_i81_322735_isactive { get; set; }
        public float Settings_fronius_inverters_i81_322735_l1energy { get; set; }
        public float Settings_fronius_inverters_i81_322735_l2energy { get; set; }
        public float Settings_fronius_inverters_i81_322735_l3energy { get; set; }
        public int Settings_fronius_inverters_i81_322735_phase { get; set; }
        public int Settings_fronius_inverters_i81_322735_phasecount { get; set; }
        public int Settings_fronius_inverters_i81_322735_position { get; set; }
        public string Settings_fronius_inverters_i81_322735_serialnumber { get; set; }
        public string Settings_fronius_inverters_i81_358494_customname { get; set; }
        public int Settings_fronius_inverters_i81_358494_isactive { get; set; }
        public float Settings_fronius_inverters_i81_358494_l1energy { get; set; }
        public float Settings_fronius_inverters_i81_358494_l2energy { get; set; }
        public float Settings_fronius_inverters_i81_358494_l3energy { get; set; }
        public int Settings_fronius_inverters_i81_358494_phase { get; set; }
        public int Settings_fronius_inverters_i81_358494_phasecount { get; set; }
        public int Settings_fronius_inverters_i81_358494_position { get; set; }
        public string Settings_fronius_inverters_i81_358494_serialnumber { get; set; }
        public string Settings_fronius_inverters_i81_639777_customname { get; set; }
        public int Settings_fronius_inverters_i81_639777_isactive { get; set; }
        public float Settings_fronius_inverters_i81_639777_l1energy { get; set; }
        public float Settings_fronius_inverters_i81_639777_l2energy { get; set; }
        public float Settings_fronius_inverters_i81_639777_l3energy { get; set; }
        public int Settings_fronius_inverters_i81_639777_phase { get; set; }
        public int Settings_fronius_inverters_i81_639777_phasecount { get; set; }
        public int Settings_fronius_inverters_i81_639777_position { get; set; }
        public string Settings_fronius_inverters_i81_639777_serialnumber { get; set; }
        public string Settings_fronius_knownipaddresses { get; set; }
        public int Settings_fronius_portnumber { get; set; }
        public int Settings_generator0_acload_enabled { get; set; }
        public int Settings_generator0_acload_measurement { get; set; }
        public int Settings_generator0_acload_quiethoursstartvalue { get; set; }
        public int Settings_generator0_acload_quiethoursstopvalue { get; set; }
        public int Settings_generator0_acload_starttimer { get; set; }
        public int Settings_generator0_acload_startvalue { get; set; }
        public int Settings_generator0_acload_stoptimer { get; set; }
        public int Settings_generator0_acload_stopvalue { get; set; }
        public string Settings_generator0_accumulateddaily { get; set; }
        public int Settings_generator0_accumulatedtotal { get; set; }
        public int Settings_generator0_alarms_nogeneratoratacin { get; set; }
        public int Settings_generator0_autostartenabled { get; set; }
        public int Settings_generator0_batterycurrent_enabled { get; set; }
        public float Settings_generator0_batterycurrent_quiethoursstartvalue { get; set; }
        public float Settings_generator0_batterycurrent_quiethoursstopvalue { get; set; }
        public int Settings_generator0_batterycurrent_starttimer { get; set; }
        public float Settings_generator0_batterycurrent_startvalue { get; set; }
        public int Settings_generator0_batterycurrent_stoptimer { get; set; }
        public float Settings_generator0_batterycurrent_stopvalue { get; set; }
        public string Settings_generator0_batteryservice { get; set; }
        public int Settings_generator0_batteryvoltage_enabled { get; set; }
        public float Settings_generator0_batteryvoltage_quiethoursstartvalue { get; set; }
        public float Settings_generator0_batteryvoltage_quiethoursstopvalue { get; set; }
        public int Settings_generator0_batteryvoltage_starttimer { get; set; }
        public float Settings_generator0_batteryvoltage_startvalue { get; set; }
        public int Settings_generator0_batteryvoltage_stoptimer { get; set; }
        public float Settings_generator0_batteryvoltage_stopvalue { get; set; }
        public int Settings_generator0_inverterhightemp_enabled { get; set; }
        public int Settings_generator0_inverterhightemp_starttimer { get; set; }
        public int Settings_generator0_inverterhightemp_stoptimer { get; set; }
        public int Settings_generator0_inverteroverload_enabled { get; set; }
        public int Settings_generator0_inverteroverload_starttimer { get; set; }
        public int Settings_generator0_inverteroverload_stoptimer { get; set; }
        public int Settings_generator0_minimumruntime { get; set; }
        public int Settings_generator0_onlosscommunication { get; set; }
        public int Settings_generator0_quiethours_enabled { get; set; }
        public int Settings_generator0_quiethours_endtime { get; set; }
        public int Settings_generator0_quiethours_starttime { get; set; }
        public int Settings_generator0_soc_enabled { get; set; }
        public int Settings_generator0_soc_quiethoursstartvalue { get; set; }
        public int Settings_generator0_soc_quiethoursstopvalue { get; set; }
        public int Settings_generator0_soc_startvalue { get; set; }
        public int Settings_generator0_soc_stopvalue { get; set; }
        public int Settings_generator0_stopwhenac1available { get; set; }
        public int Settings_generator0_testrun_duration { get; set; }
        public int Settings_generator0_testrun_enabled { get; set; }
        public int Settings_generator0_testrun_interval { get; set; }
        public int Settings_generator0_testrun_runtillbatteryfull { get; set; }
        public int Settings_generator0_testrun_skipruntime { get; set; }
        public int Settings_generator0_testrun_startdate { get; set; }
        public int Settings_generator0_testrun_starttime { get; set; }
        public int Settings_gps_format { get; set; }
        public string Settings_gps_speedunit { get; set; }
        public int Settings_gui_autobrightness { get; set; }
        public int Settings_gui_brightness { get; set; }
        public string Settings_gui_defaultoverview { get; set; }
        public int Settings_gui_demomode { get; set; }
        public int Settings_gui_displayoff { get; set; }
        public string Settings_gui_language { get; set; }
        public int Settings_gui_mobileoverview { get; set; }
        public int Settings_gui_startwithmenuview { get; set; }
        public int Settings_gui_tanksoverview { get; set; }
        public int Settings_modbusclient_tcp_autoscan { get; set; }
        public int Settings_modbusclient_ttyusb0_autoscan { get; set; }
        public int Settings_modbusclient_ttyusb1_autoscan { get; set; }
        public int Settings_pump0_autostartenabled { get; set; }
        public int Settings_pump0_mode { get; set; }
        public int Settings_pump0_startvalue { get; set; }
        public int Settings_pump0_stopvalue { get; set; }
        public string Settings_pump0_tankservice { get; set; }
        public int Settings_relay_0_initialstate { get; set; }
        public int Settings_relay_1_function { get; set; }
        public int Settings_relay_1_initialstate { get; set; }
        public int Settings_relay_1_polarity { get; set; }
        public int Settings_relay_function { get; set; }
        public int Settings_relay_polarity { get; set; }
        public string Settings_sensors_onposition_acin1_l1 { get; set; }
        public string Settings_sensors_onposition_acin1_l2 { get; set; }
        public string Settings_sensors_onposition_acin1_l3 { get; set; }
        public string Settings_sensors_onposition_acin2_l1 { get; set; }
        public string Settings_sensors_onposition_acin2_l2 { get; set; }
        public string Settings_sensors_onposition_acin2_l3 { get; set; }
        public string Settings_sensors_onposition_acout_l1 { get; set; }
        public string Settings_sensors_onposition_acout_l2 { get; set; }
        public string Settings_sensors_onposition_acout_l3 { get; set; }
        public int Settings_services_accesspoint { get; set; }
        public int Settings_services_blesensors { get; set; }
        public int Settings_services_bluetooth { get; set; }
        public int Settings_services_bol { get; set; }
        public int Settings_services_console { get; set; }
        public int Settings_services_fischerpandaautostartstop { get; set; }
        public int Settings_services_modbus { get; set; }
        public int Settings_services_mqttlocal { get; set; }
        public int Settings_services_mqttlocalinsecure { get; set; }
        public int Settings_services_mqttn2k { get; set; }
        public int Settings_services_mqttvrm { get; set; }
        public int Settings_services_nodered { get; set; }
        public int Settings_services_signalk { get; set; }
        public int Settings_services_socketcand { get; set; }
        public int Settings_system_accesslevel { get; set; }
        public int Settings_system_activenetworkconnection { get; set; }
        public int Settings_system_autoupdate { get; set; }
        public int Settings_system_imagetype { get; set; }
        public int Settings_system_loglevel { get; set; }
        public int Settings_system_releasetype { get; set; }
        public int Settings_system_remotesupport { get; set; }
        public string Settings_system_remotesupportipandport { get; set; }
        public int Settings_system_sshlocal { get; set; }
        public string Settings_system_timezone { get; set; }
        public string Settings_system_units_temperature { get; set; }
        public int Settings_system_vncinternet { get; set; }
        public int Settings_system_vnclocal { get; set; }
        public int Settings_system_volumeunit { get; set; }
        public int Settings_systemsetup_acinput1 { get; set; }
        public int Settings_systemsetup_acinput2 { get; set; }
        public int Settings_systemsetup_batteries_configuration_com_victronenergy_battery_0_1_enabled { get; set; }
        public string Settings_systemsetup_batteries_configuration_com_victronenergy_battery_0_1_name { get; set; }
        public string Settings_systemsetup_batteries_configuration_com_victronenergy_battery_0_1_service { get; set; }
        public int Settings_systemsetup_batteries_configuration_com_victronenergy_battery_0_enabled { get; set; }
        public string Settings_systemsetup_batteries_configuration_com_victronenergy_battery_0_name { get; set; }
        public string Settings_systemsetup_batteries_configuration_com_victronenergy_battery_0_service { get; set; }
        public int Settings_systemsetup_batteries_configuration_com_victronenergy_battery_279_1_enabled { get; set; }
        public string Settings_systemsetup_batteries_configuration_com_victronenergy_battery_279_1_name { get; set; }
        public string Settings_systemsetup_batteries_configuration_com_victronenergy_battery_279_1_service { get; set; }
        public int Settings_systemsetup_batteries_configuration_com_victronenergy_battery_279_enabled { get; set; }
        public string Settings_systemsetup_batteries_configuration_com_victronenergy_battery_279_name { get; set; }
        public string Settings_systemsetup_batteries_configuration_com_victronenergy_battery_279_service { get; set; }
        public int Settings_systemsetup_batteries_configuration_com_victronenergy_battery_512_1_enabled { get; set; }
        public string Settings_systemsetup_batteries_configuration_com_victronenergy_battery_512_1_name { get; set; }
        public string Settings_systemsetup_batteries_configuration_com_victronenergy_battery_512_1_service { get; set; }
        public int Settings_systemsetup_batteries_configuration_com_victronenergy_battery_512_enabled { get; set; }
        public string Settings_systemsetup_batteries_configuration_com_victronenergy_battery_512_name { get; set; }
        public string Settings_systemsetup_batteries_configuration_com_victronenergy_battery_512_service { get; set; }
        public int Settings_systemsetup_batteries_configuration_com_victronenergy_vebus_276_enabled { get; set; }
        public string Settings_systemsetup_batteries_configuration_com_victronenergy_vebus_276_name { get; set; }
        public string Settings_systemsetup_batteries_configuration_com_victronenergy_vebus_276_service { get; set; }
        public int Settings_systemsetup_batterycurrentsense { get; set; }
        public string Settings_systemsetup_batteryservice { get; set; }
        public int Settings_systemsetup_hasacoutsystem { get; set; }
        public int Settings_systemsetup_hasdcsystem { get; set; }
        public int Settings_systemsetup_maxchargecurrent { get; set; }
        public float Settings_systemsetup_maxchargevoltage { get; set; }
        public int Settings_systemsetup_sharedtemperaturesense { get; set; }
        public int Settings_systemsetup_sharedvoltagesense { get; set; }
        public string Settings_systemsetup_systemname { get; set; }
        public string Settings_systemsetup_temperatureservice { get; set; }
        public int Settings_vecan_can0_freeidentitynumber { get; set; }
        public string Settings_vecan_can0_maininterface_description2 { get; set; }
        public int Settings_vecan_can0_maininterface_identitynumber { get; set; }
        public int Settings_vecan_can0_maininterface_instance { get; set; }
        public int Settings_vecan_can0_maininterface_nad { get; set; }
        public int Settings_vecan_can0_maininterface_systeminstance { get; set; }
        public int Settings_vecan_can0_n2kgatewayenabled { get; set; }
        public int Settings_vecan_can0_venusuniqueid { get; set; }
        public int Settings_venusapp_lockbuttonstate { get; set; }
        public string Settings_victron_products_hq202952stb_customname { get; set; }
        public string Settings_victron_products_hq2036paz1j_customname { get; set; }
        public string Settings_victron_products_hq2041913yf_customname { get; set; }
        public string Settings_victron_products_hq2107u59k7_customname { get; set; }
        public string Settings_victron_products_hq21399mdky_customname { get; set; }
        public string Settings_vrmlogger_externalstoragedir { get; set; }
        public string Settings_vrmlogger_http_proxy { get; set; }
        public string Settings_vrmlogger_http_proxyport { get; set; }
        public int Settings_vrmlogger_httpsenabled { get; set; }
        public int Settings_vrmlogger_loginterval { get; set; }
        public int Settings_vrmlogger_logmode { get; set; }
        public int Settings_vrmlogger_ramdiskmode { get; set; }
        public string Settings_vrmlogger_url { get; set; }
        public int Settings_watchdog_vrmtimeout { get; set; }
    }

    public class SettingsDevice
    {
        public string Classandvrminstance { get; set; }
        public int Alarms_high_active { get; set; }
        public int Alarms_high_delay { get; set; }
        public int Alarms_high_enable { get; set; }
        public int Alarms_high_restore { get; set; }
        public int Alarms_low_active { get; set; }
        public int Alarms_low_delay { get; set; }
        public int Alarms_low_enable { get; set; }
        public int Alarms_low_restore { get; set; }
        public float Capacity { get; set; }
        public string Customname { get; set; }
        public int Filterlength { get; set; }
        public int Fluidtype2 { get; set; }
        public int Function { get; set; }
        public float Rawvalueempty { get; set; }
        public float Rawvaluefull { get; set; }
        public string Shape { get; set; }
        public int Standard2 { get; set; }
        public float Offset { get; set; }
        public float Scale { get; set; }
        public int Temperaturetype2 { get; set; }
        public int Ismultiphase { get; set; }
        public float L1reverseenergy { get; set; }
        public float L2reverseenergy { get; set; }
        public float L3reverseenergy { get; set; }
        public int Position { get; set; }
        public int Supportmultiphase { get; set; }
        public int Enabled { get; set; }
    }

    public class Tank
    {
        public int Alarms_high_active { get; set; }
        public int Alarms_high_delay { get; set; }
        public int Alarms_high_enable { get; set; }
        public int Alarms_high_restore { get; set; }
        public object Alarms_high_state { get; set; }
        public int Alarms_low_active { get; set; }
        public int Alarms_low_delay { get; set; }
        public int Alarms_low_enable { get; set; }
        public int Alarms_low_restore { get; set; }
        public object Alarms_low_state { get; set; }
        public float Capacity { get; set; }
        public int Connected { get; set; }
        public string Customname { get; set; }
        public int Deviceinstance { get; set; }
        public int Filterlength { get; set; }
        public int Fluidtype { get; set; }
        public object Level { get; set; }
        public string Mgmt_connection { get; set; }
        public string Mgmt_processname { get; set; }
        public string Mgmt_processversion { get; set; }
        public int Productid { get; set; }
        public string Productname { get; set; }
        public string Rawunit { get; set; }
        public float Rawvalue { get; set; }
        public float Rawvalueempty { get; set; }
        public float Rawvaluefull { get; set; }
        public object Remaining { get; set; }
        public string Shape { get; set; }
        public int Standard { get; set; }
        public int Status { get; set; }
    }

    public class Vecan
    {
        public int Alarms_sameuniquenameused { get; set; }
        public List<VecanDevice> Devices { get; set; } = new List<VecanDevice> ();
        public object Link_batterycurrent { get; set; }
        public float Link_chargevoltage { get; set; }
        public float Link_extrabatterycurrent { get; set; }
        public int Link_networkmode { get; set; }
        public object Link_soc { get; set; }
        public float Link_temperaturesense { get; set; }
        public float Link_voltagesense { get; set; }
    }

    public class VecanDevice
    {
        public string Customname { get; set; }
        public int Deviceinstance { get; set; }
        public string Firmwareversion { get; set; }
        public int Manufacturer { get; set; }
        public string Modelname { get; set; }
        public int N2kuniquenumber { get; set; }
        public int Nad { get; set; }
        public string Serial { get; set; }
    }



}